import { lazy } from 'react'
import type { ToolDefinition, CategoryId } from './types'

export const tools: ToolDefinition[] = [
  // ── Formatters & Beautifiers ──────────────────────────
  {
    slug: 'json-formatter',
    name: 'JSON Formatter / Validator',
    description: 'Format, validate, and minify JSON',
    category: 'formatters',
    keywords: ['json', 'format', 'validate', 'prettify', 'minify', 'lint'],
    component: lazy(() => import('@/tools/formatters/json-formatter')),
  },
  {
    slug: 'xml-formatter',
    name: 'XML Formatter / Validator',
    description: 'Format and validate XML documents',
    category: 'formatters',
    keywords: ['xml', 'format', 'validate', 'prettify'],
    component: lazy(() => import('@/tools/formatters/xml-formatter')),
  },
  {
    slug: 'html-formatter',
    name: 'HTML Formatter / Beautifier',
    description: 'Format and beautify HTML markup',
    category: 'formatters',
    keywords: ['html', 'format', 'beautify', 'prettify'],
    component: lazy(() => import('@/tools/formatters/html-formatter')),
  },
  {
    slug: 'css-formatter',
    name: 'CSS Formatter / Minifier',
    description: 'Format or minify CSS stylesheets',
    category: 'formatters',
    keywords: ['css', 'format', 'minify', 'beautify', 'stylesheet'],
    component: lazy(() => import('@/tools/formatters/css-formatter')),
  },
  {
    slug: 'js-ts-formatter',
    name: 'JS/TS Formatter',
    description: 'Format JavaScript and TypeScript code',
    category: 'formatters',
    keywords: ['javascript', 'typescript', 'format', 'prettify', 'js', 'ts'],
    component: lazy(() => import('@/tools/formatters/js-ts-formatter')),
  },
  {
    slug: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format SQL queries for readability',
    category: 'formatters',
    keywords: ['sql', 'format', 'query', 'prettify', 'database'],
    component: lazy(() => import('@/tools/formatters/sql-formatter')),
  },
  {
    slug: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Preview Markdown with syntax highlighting',
    category: 'formatters',
    keywords: ['markdown', 'preview', 'md', 'render'],
    component: lazy(() => import('@/tools/formatters/markdown-preview')),
  },
  {
    slug: 'yaml-formatter',
    name: 'YAML Formatter',
    description: 'Format and validate YAML documents',
    category: 'formatters',
    keywords: ['yaml', 'yml', 'format', 'validate'],
    component: lazy(() => import('@/tools/formatters/yaml-formatter')),
  },

  // ── Encoders & Decoders ───────────────────────────────
  {
    slug: 'base64-encode-decode',
    name: 'Base64 Encode/Decode',
    description: 'Encode or decode text as Base64',
    category: 'encoders',
    keywords: ['base64', 'encode', 'decode', 'text'],
    component: lazy(() => import('@/tools/encoders/base64-text')),
  },
  {
    slug: 'base64-file',
    name: 'Base64 File Encoder',
    description: 'Convert files to and from Base64',
    category: 'encoders',
    keywords: ['base64', 'file', 'encode', 'decode', 'image'],
    component: lazy(() => import('@/tools/encoders/base64-file')),
  },
  {
    slug: 'url-encode-decode',
    name: 'URL Encode / Decode',
    description: 'Encode or decode URL components',
    category: 'encoders',
    keywords: ['url', 'encode', 'decode', 'percent', 'uri'],
    component: lazy(() => import('@/tools/encoders/url-encode-decode')),
  },
  {
    slug: 'html-entity-encode-decode',
    name: 'HTML Entity Encode/Decode',
    description: 'Encode or decode HTML entities',
    category: 'encoders',
    keywords: ['html', 'entity', 'encode', 'decode', 'escape'],
    component: lazy(() => import('@/tools/encoders/html-entity')),
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens',
    category: 'encoders',
    keywords: ['jwt', 'json', 'web', 'token', 'decode', 'auth'],
    component: lazy(() => import('@/tools/encoders/jwt-decoder')),
  },
  {
    slug: 'unicode-escape',
    name: 'Unicode Escape/Unescape',
    description: 'Escape or unescape Unicode characters',
    category: 'encoders',
    keywords: ['unicode', 'escape', 'unescape', 'utf', 'character'],
    component: lazy(() => import('@/tools/encoders/unicode-escape')),
  },

  // ── String / Text Tools ───────────────────────────────
  {
    slug: 'string-escape',
    name: 'String Escape / Unescape',
    description: 'Escape or unescape strings for various languages',
    category: 'string-text',
    keywords: ['string', 'escape', 'unescape', 'quote'],
    component: lazy(() => import('@/tools/string-text/string-escape')),
  },
  {
    slug: 'text-case-converter',
    name: 'Text Case Converter',
    description: 'Convert text between camelCase, snake_case, UPPER, etc.',
    category: 'string-text',
    keywords: ['case', 'convert', 'camel', 'snake', 'pascal', 'upper', 'lower', 'kebab'],
    component: lazy(() => import('@/tools/string-text/text-case-converter')),
  },
  {
    slug: 'text-diff',
    name: 'Text Diff / Compare',
    description: 'Compare two texts and highlight differences',
    category: 'string-text',
    keywords: ['diff', 'compare', 'difference', 'merge'],
    component: lazy(() => import('@/tools/string-text/text-diff')),
  },
  {
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text',
    category: 'string-text',
    keywords: ['lorem', 'ipsum', 'placeholder', 'dummy', 'text'],
    component: lazy(() => import('@/tools/string-text/lorem-ipsum')),
  },
  {
    slug: 'word-counter',
    name: 'Word / Character Counter',
    description: 'Count words, characters, sentences, and paragraphs',
    category: 'string-text',
    keywords: ['word', 'character', 'count', 'length', 'sentence'],
    component: lazy(() => import('@/tools/string-text/word-counter')),
  },
  {
    slug: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    description: 'Remove duplicate lines from text',
    category: 'string-text',
    keywords: ['duplicate', 'remove', 'unique', 'lines', 'deduplicate'],
    component: lazy(() => import('@/tools/string-text/remove-duplicate-lines')),
  },
  {
    slug: 'sort-lines',
    name: 'Sort Lines',
    description: 'Sort lines alphabetically, numerically, or by length',
    category: 'string-text',
    keywords: ['sort', 'lines', 'alphabetical', 'order', 'reverse'],
    component: lazy(() => import('@/tools/string-text/sort-lines')),
  },
  {
    slug: 'reverse-string',
    name: 'Reverse String / Lines',
    description: 'Reverse text or individual lines',
    category: 'string-text',
    keywords: ['reverse', 'string', 'lines', 'flip', 'backwards'],
    component: lazy(() => import('@/tools/string-text/reverse-string')),
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with live highlighting',
    category: 'string-text',
    keywords: ['regex', 'regular', 'expression', 'test', 'match', 'pattern'],
    component: lazy(() => import('@/tools/string-text/regex-tester')),
  },
  {
    slug: 'backslash-escape',
    name: 'Backslash Escape/Unescape',
    description: 'Escape or unescape backslash sequences',
    category: 'string-text',
    keywords: ['backslash', 'escape', 'unescape', 'newline', 'tab'],
    component: lazy(() => import('@/tools/string-text/backslash-escape')),
  },

  // ── Hash & Crypto ─────────────────────────────────────
  {
    slug: 'hash-generator',
    name: 'Hash Generator (MD5/SHA)',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes',
    category: 'hash-crypto',
    keywords: ['hash', 'md5', 'sha', 'sha256', 'sha512', 'checksum'],
    component: lazy(() => import('@/tools/hash-crypto/hash-generator')),
  },
  {
    slug: 'hmac-generator',
    name: 'HMAC Generator',
    description: 'Generate HMAC signatures with a secret key',
    category: 'hash-crypto',
    keywords: ['hmac', 'hash', 'signature', 'secret', 'key', 'auth'],
    component: lazy(() => import('@/tools/hash-crypto/hmac-generator')),
  },
  {
    slug: 'uuid-generator',
    name: 'UUID / GUID Generator',
    description: 'Generate UUIDs (v4 and v7)',
    category: 'hash-crypto',
    keywords: ['uuid', 'guid', 'unique', 'identifier', 'v4', 'v7'],
    component: lazy(() => import('@/tools/hash-crypto/uuid-generator')),
  },
  {
    slug: 'ulid-generator',
    name: 'ULID Generator',
    description: 'Generate ULIDs (Universally Unique Lexicographically Sortable Identifiers)',
    category: 'hash-crypto',
    keywords: ['ulid', 'unique', 'identifier', 'sortable'],
    component: lazy(() => import('@/tools/hash-crypto/ulid-generator')),
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong random passwords',
    category: 'hash-crypto',
    keywords: ['password', 'generate', 'random', 'strong', 'secure'],
    component: lazy(() => import('@/tools/hash-crypto/password-generator')),
  },
  {
    slug: 'bcrypt',
    name: 'Bcrypt Hash / Verify',
    description: 'Hash and verify passwords with bcrypt',
    category: 'hash-crypto',
    keywords: ['bcrypt', 'hash', 'verify', 'password'],
    component: lazy(() => import('@/tools/hash-crypto/bcrypt-tool')),
  },

  // ── Converters ────────────────────────────────────────
  {
    slug: 'json-yaml',
    name: 'JSON ↔ YAML',
    description: 'Convert between JSON and YAML formats',
    category: 'converters',
    keywords: ['json', 'yaml', 'convert', 'transform'],
    component: lazy(() => import('@/tools/converters/json-yaml')),
  },
  {
    slug: 'json-csv',
    name: 'JSON ↔ CSV',
    description: 'Convert between JSON and CSV formats',
    category: 'converters',
    keywords: ['json', 'csv', 'convert', 'spreadsheet', 'table'],
    component: lazy(() => import('@/tools/converters/json-csv')),
  },
  {
    slug: 'json-to-typescript',
    name: 'JSON → TypeScript',
    description: 'Generate TypeScript interfaces from JSON',
    category: 'converters',
    keywords: ['json', 'typescript', 'interface', 'type', 'generate'],
    component: lazy(() => import('@/tools/converters/json-to-typescript')),
  },
  {
    slug: 'json-to-go-struct',
    name: 'JSON → Go Struct',
    description: 'Generate Go structs from JSON',
    category: 'converters',
    keywords: ['json', 'go', 'golang', 'struct', 'generate'],
    component: lazy(() => import('@/tools/converters/json-to-go-struct')),
  },
  {
    slug: 'number-base-converter',
    name: 'Number Base Converter',
    description: 'Convert numbers between binary, octal, decimal, and hex',
    category: 'converters',
    keywords: ['number', 'base', 'binary', 'hex', 'octal', 'decimal', 'convert'],
    component: lazy(() => import('@/tools/converters/number-base')),
  },
  {
    slug: 'color-converter',
    name: 'Color Converter / Picker',
    description: 'Convert colors between HEX, RGB, HSL, and more',
    category: 'converters',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'convert', 'picker'],
    component: lazy(() => import('@/tools/converters/color-converter')),
  },
  {
    slug: 'unix-timestamp',
    name: 'Unix Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates',
    category: 'converters',
    keywords: ['unix', 'timestamp', 'epoch', 'date', 'time', 'convert'],
    component: lazy(() => import('@/tools/converters/unix-timestamp')),
  },
  {
    slug: 'cron-parser',
    name: 'Cron Expression Parser',
    description: 'Parse and explain cron schedule expressions',
    category: 'converters',
    keywords: ['cron', 'schedule', 'expression', 'parse', 'job'],
    component: lazy(() => import('@/tools/converters/cron-parser')),
  },
  {
    slug: 'json-path',
    name: 'JSON Path Evaluator',
    description: 'Evaluate JSONPath expressions against JSON data',
    category: 'converters',
    keywords: ['json', 'path', 'jsonpath', 'query', 'evaluate'],
    component: lazy(() => import('@/tools/converters/json-path')),
  },
  {
    slug: 'px-rem-converter',
    name: 'Px ↔ Rem Converter',
    description: 'Convert between pixels and rem units',
    category: 'converters',
    keywords: ['px', 'rem', 'pixel', 'convert', 'css', 'font'],
    component: lazy(() => import('@/tools/converters/px-rem-converter')),
  },

  // ── Web / Network ─────────────────────────────────────
  {
    slug: 'http-status-codes',
    name: 'HTTP Status Code Reference',
    description: 'Look up HTTP status codes and their meanings',
    category: 'web-network',
    keywords: ['http', 'status', 'code', 'response', 'api', '404', '500'],
    component: lazy(() => import('@/tools/web-network/http-status-codes')),
  },
  {
    slug: 'mime-type-lookup',
    name: 'MIME Type Lookup',
    description: 'Look up MIME types by file extension',
    category: 'web-network',
    keywords: ['mime', 'type', 'content', 'extension', 'file'],
    component: lazy(() => import('@/tools/web-network/mime-type-lookup')),
  },
  {
    slug: 'url-parser',
    name: 'URL Parser',
    description: 'Parse and inspect URL components',
    category: 'web-network',
    keywords: ['url', 'parse', 'query', 'path', 'host', 'protocol'],
    component: lazy(() => import('@/tools/web-network/url-parser')),
  },
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text or URLs',
    category: 'web-network',
    keywords: ['qr', 'code', 'generate', 'barcode', 'scan'],
    component: lazy(() => import('@/tools/web-network/qr-code-generator')),
  },
  {
    slug: 'svg-preview',
    name: 'SVG Preview / Optimizer',
    description: 'Preview and optimize SVG files',
    category: 'web-network',
    keywords: ['svg', 'preview', 'optimize', 'vector', 'image'],
    component: lazy(() => import('@/tools/web-network/svg-preview')),
  },

  // ── Data Generators ───────────────────────────────────
  {
    slug: 'mock-data-generator',
    name: 'Mock Data Generator',
    description: 'Generate realistic mock data for testing',
    category: 'data-generators',
    keywords: ['mock', 'data', 'fake', 'generate', 'test', 'faker'],
    component: lazy(() => import('@/tools/data-generators/mock-data-generator')),
  },
  {
    slug: 'random-generator',
    name: 'Random Number/String Generator',
    description: 'Generate random numbers and strings',
    category: 'data-generators',
    keywords: ['random', 'number', 'string', 'generate'],
    component: lazy(() => import('@/tools/data-generators/random-generator')),
  },
]

// Derived lookup maps
export const toolsBySlug = new Map(tools.map((t) => [t.slug, t]))

export function getToolsByCategory(categoryId: CategoryId): ToolDefinition[] {
  return tools.filter((t) => t.category === categoryId)
}
